// Code generated by mockery v2.32.0. DO NOT EDIT.

package functions_mocks

import mock "github.com/stretchr/testify/mock"

// IAppPathGenerator is an autogenerated mock type for the IAppPathGenerator type
type IAppPathGenerator struct {
	mock.Mock
}

// CreateAppPath provides a mock function with given fields: path
func (_m *IAppPathGenerator) CreateAppPath(path string) error {
	ret := _m.Called(path)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(path)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GenerateAppCode provides a mock function with given fields: code
func (_m *IAppPathGenerator) GenerateAppCode(code string) error {
	ret := _m.Called(code)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(code)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewIAppPathGenerator creates a new instance of IAppPathGenerator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIAppPathGenerator(t interface {
	mock.TestingT
	Cleanup(func())
}) *IAppPathGenerator {
	mock := &IAppPathGenerator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
