database:
    driver: mysql
    host: localhost
    port: 3306
    username: user
    password: password
    name: database
    sslmode: disable
    max_idle_conn: 30
    max_open_conn: 20
    life_time_conn: 40
