
[database]
  driver = "mysql"
  host = "localhost"
  life_time_conn = 40
  max_idle_conn = 30
  max_open_conn = 20
  name = "database"
  password = "password"
  port = 3306
  sslmode = "disable"
  username = "user"
